### ISSUE TITLE
ImportError: No module named 'cairocffi'

### ISSUE THREAD

**Issue by chamathkv** [conda-forge/cairo-feedstock#29]
Hello,

I need to install cairocffi in order to use some example files from scikit-rf. However even though I used `pip install cairocffi`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-2.2.0-py3.5-linux-armv7l.egg/matplotlib/backends/backend_cairo.py", line 24, in <module>
    import cairocffi as cairo
ImportError: No module named 'cairocffi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-2.2.0-py3.5-linux-armv7l.egg/matplotlib/backends/backend_cairo.py", line 27, in <module>
    import cairo
ImportError: No module named 'cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/Backup/scikit-rf-master/skrf/plotting.py", line 40, in <module>
    import matplotlib.pyplot as plb
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-2.2.0-py3.5-linux-armv7l.egg/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-2.2.0-py3.5-linux-armv7l.egg/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-2.2.0-py3.5-linux-armv7l.egg/matplotlib/backends/backend_gtk3agg.py", line 10, in <module>
    from .backend_cairo import cairo, HAS_CAIRO_CFFI
  File "/usr/local/lib/python3.5/dist-packages/matplotlib-2.2.0-py3.5-linux-armv7l.egg/matplotlib/backends/backend_cairo.py", line 29, in <module>
    raise ImportError("cairo backend requires that cairocffi or pycairo "
ImportError: cairo backend requires that cairocffi or pycairo is installed
```
Checking on pip freeze does show cairocffi listed but I can't understand why this code cannot read it.
Any help would be greatly appreciated.

**Comment by chamathkv** [comment]
Figured out the issue was with different commands for python 2 and python 3. Just needed to add `pip3 install cairocffi`.

**Comment by pkgw** [comment]
There is definitely a problem here in that the difference between libraries and Python modules is not obvious to people unless they're familiar with the packages in question, but that problem is beyond the scope of just Cairo. Closing this.
